apiVersion: v1
kind: Service
metadata:
  name: imgstore-backend
spec:
  type: LoadBalancer
  selector:
    app: api-server
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: imgstore-backend
  labels:
    app: api-server
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api-server
  template:
    metadata:
      labels:
        app: api-server
    spec:
      containers:
      - name: api-server
        image: imgstore-backend:0.0.1-SNAPSHOT
        # to use local docker image
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        env:
          - name: MYSQL_URL
            value: "jdbc:mysql://imgstore-mysql/imgstore"
          - name: MYSQL_USER
            value: root
          - name: MYSQL_PASSWORD
            value: rootPassword
          - name: MYSQL_SCHEMA
            value: imgstore
