apiVersion: v1
kind: Service
metadata:
  name: imgstore-frontend
spec:
  type: LoadBalancer
  selector:
    app: web-server
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: imgstore-frontend
  labels:
    app: web-server
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web-server
  template:
    metadata:
      labels:
        app: web-server
    spec:
      containers:
      - name: web-server
        image: imgstore-frontend
        # to use local docker image
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
